name: AlpineLLM - Component Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  component-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dependencies
        uses: ./.github/actions/dependency_setup
        with:
          python-version: '3.10'

      - name: Download dataset
        run: |
          bash core/utils/download_dataset.sh
      - name: Run pre-processing
        run: |
          python run_preprocessing.py

      - name: Data loader unit test
        run: |
          python3 -m core.dataloaders.dataloader_llm --split-name test --data-dir ./PREPROCESSED_DATA/P01
      - name: Evaluator unit test
        run: |
          python3 -m core.evaluators.evaluator_llm
