name: Default Github Actions for AlpineLLM

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  # ==========================
  # Pre-processing job
  # ==========================
  pre-processing:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dependencies
        uses: ./.github/actions/dependency_setup
        with:
          python-version: '3.10'

      - name: Download dataset
        run: |
          bash core/utils/download_dataset.sh
      - name: Run pre-processing
        run: |
          python run_preprocessing.py

  # ==========================
  # Training job
  # ==========================
  training:
    runs-on: ubuntu-24.04
    needs: pre-processing
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dependencies
        uses: ./.github/actions/dependency_setup
        with:
          python-version: '3.10'

      - name: Run training
        run: |
          python run_training.py --cfg-path configs/training_github_actions_cfg.yml

  # ==========================
  # Evaluation job
  # ==========================
  evaluation:
    runs-on: ubuntu-24.04
    needs: [training, pre-processing]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dependencies
        uses: ./.github/actions/dependency_setup
        with:
          python-version: '3.10'

      - name: Run evaluation
        run: |
          python run_evaluation.py
