name: AlpineLLM - Unit Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dependencies
        uses: ./.github/actions/dependency_setup
        with:
          python-version: '3.10'

      - name: Data loader unit test
        run: |
          python3 -m core.dataloaders.dataloader_llm
      - name: Evaluator unit test
        run: |
          python3 -m core.evaluators.evaluator_llm
